# Generated by Django 3.2.2 on 2021-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_emailsetting_email_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='email_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
