version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 80:80
        volumes:
            - ../nginx:/etc/nginx/conf.d     
