version: '3'

services:
    nginx: 
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 80:80
            - 3000:3000
        volumes:
            - ../nginx:/etc/nginx/conf.d     
