# Generated by Django 3.1.2 on 2020-12-09 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0009_remove_blogpost_opened'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostOpened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened', to='blogs.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_opened', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
