# Generated by Django 3.1.2 on 2021-03-23 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0009_remove_blogpost_opened'),
        ('users', '0004_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsubscriber',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_by', to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='blogsubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to=settings.AUTH_USER_MODEL),
        ),
    ]
