# Generated by Django 3.2.2 on 2021-06-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210519_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='email_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('none', 'None')], default='daily', max_length=100),
        ),
    ]
