version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    working_directory: ~/backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd backend
            pip install -r requirements.txt
          name: Installing requirements
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          command: |
            ls
            . venv/bin/activate
            cd backend/blogs_manager 
            python manage.py test
          name: Running tests

workflows:
  main:
    jobs:
      - build-and-test