version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    working_directory: ~/backend
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            ..
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          name: Installing requirements
      - python/save-cache
      - run:
          command: cd blogs_manager && python manage.py test
          name: Running tests

workflows:
  main:
    jobs:
      - build-and-test