# Generated by Django 3.1.2 on 2020-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201107_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='icon',
            field=models.TextField(blank=True),
        ),
    ]
