export const GET_BLOG_POSTS_REQUEST = 'GET_BLOG_POSTS_REQUEST';
export const GET_BLOG_POSTS_SUCCESS = 'GET_BLOG_POSTS_SUCCESS';
export const GET_BLOG_POSTS_FAILURE = 'GET_BLOG_POSTS_FAILURE';

export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE';

export const POST_SUBSCRIBE_BLOG_REQUEST = 'POST_SUBSCRIBE_BLOG_REQUEST';
export const POST_SUBSCRIBE_BLOG_SUCCESS = 'POST_SUBSCRIBE_BLOG_SUCCESS';
export const POST_SUBSCRIBE_BLOG_FAILURE = 'POST_SUBSCRIBE_BLOG_FAILURE';

export const GET_SUBSCRIBED_BLOGS_REQUEST = 'GET_SUBSCRIBED_BLOGS_REQUEST';
export const GET_SUBSCRIBED_BLOGS_SUCCESS = 'GET_SUBSCRIBED_BLOGS_SUCCESS';
export const GET_SUBSCRIBED_BLOGS_FAILURE = 'GET_SUBSCRIBED_BLOGS_FAILURE';

export const GET_SUBSCRIBED_BLOG_POSTS_REQUEST = 'GET_SUBSCRIBED_BLOG_POSTS_REQUEST';
export const GET_SUBSCRIBED_BLOG_POSTS_SUCCESS = 'GET_SUBSCRIBED_BLOG_POSTS_SUCCESS';
export const GET_SUBSCRIBED_BLOG_POSTS_FAILURE = 'GET_SUBSCRIBED_BLOG_POSTS_FAILURE';

export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST';
export const GET_BLOG_DETAILS_SUCCESS = 'GET_BLOG_DETAILS_SUCCESS';
export const GET_BLOG_DETAILS_FAILURE = 'GET_BLOG_DETAILS_FAILURE';

export const GET_BLOG_PHOTO_REQUEST = 'GET_BLOG_PHOTO_REQUEST';
export const GET_BLOG_PHOTO_SUCCESS = 'GET_BLOG_PHOTO_SUCCESS';
export const GET_BLOG_PHOTO_FAILURE = 'GET_BLOG_PHOTO_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const POST_EMAIL_SETTING_REQUEST = 'POST_EMAIL_SETTING_REQUEST';
export const POST_EMAIL_SETTING_SUCCESS = 'POST_EMAIL_SETTING_SUCCESS';
export const POST_EMAIL_SETTING_FAILURE = 'POST_EMAIL_SETTING_FAILURE';

export const GET_ERRORS = 'GET_ERRORS';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';