# Generated by Django 3.1.2 on 2020-11-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_blog_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_photo', to='blogs.blog')),
            ],
        ),
    ]
