# Generated by Django 3.1.2 on 2020-12-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20201209_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='opened',
        ),
    ]
