# Generated by Django 3.1.2 on 2021-05-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_reportblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportblog',
            name='user',
        ),
    ]
